BEGIN
  DBMS_OUTPUT.PUT_LINE('=== CLEANUP START ===');
END;
/
BEGIN
  FOR r IN (SELECT trigger_name FROM user_triggers) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TRIGGER ' || r.trigger_name;
    EXCEPTION
      WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/
BEGIN
  BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE pkg_rapoarte_interactive'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE pkg_rapoarte';            EXCEPTION WHEN OTHERS THEN NULL; END;
END;
/
BEGIN
  FOR t IN (
    SELECT table_name
    FROM user_tables
    WHERE table_name IN (
      'STOC','LUCRARE','PLANTARE','UTILAJ','ANGAJAT','DEPOZIT','PARCELA','SEZON','CULTURA','FERMA'
    )
    ORDER BY CASE table_name
      WHEN 'STOC' THEN 1
      WHEN 'LUCRARE' THEN 2
      WHEN 'PLANTARE' THEN 3
      WHEN 'UTILAJ' THEN 4
      WHEN 'ANGAJAT' THEN 5
      WHEN 'DEPOZIT' THEN 6
      WHEN 'PARCELA' THEN 7
      WHEN 'SEZON' THEN 8
      WHEN 'CULTURA' THEN 9
      WHEN 'FERMA' THEN 10
      ELSE 999
    END
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    EXCEPTION
      WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/
BEGIN
  DBMS_OUTPUT.PUT_LINE('=== CLEANUP DONE ===');
END;
/
