-- 01_schema.sql

-- 1) FERMA
CREATE TABLE ferma (
  ferma_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nume         VARCHAR2(100) NOT NULL,
  localitate   VARCHAR2(100) NOT NULL
);

-- 2) PARCELA
CREATE TABLE parcela (
  parcela_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ferma_id      NUMBER NOT NULL,
  denumire      VARCHAR2(60) NOT NULL,
  suprafata_ha  NUMBER(8,2) NOT NULL,
  tip_sol       VARCHAR2(50),

  CONSTRAINT ck_parcela_suprafata CHECK (suprafata_ha > 0),
  CONSTRAINT fk_parcela_ferma FOREIGN KEY (ferma_id) REFERENCES ferma(ferma_id),
  CONSTRAINT uq_parcela_ferma_denumire UNIQUE (ferma_id, denumire)
);

-- 3) DEPOZIT
CREATE TABLE depozit (
  depozit_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ferma_id         NUMBER NOT NULL,
  nume             VARCHAR2(80) NOT NULL,
  tip              VARCHAR2(30) NOT NULL,
  capacitate_tone  NUMBER(10,2) NOT NULL,

  CONSTRAINT ck_depozit_cap CHECK (capacitate_tone > 0),
  CONSTRAINT fk_depozit_ferma FOREIGN KEY (ferma_id) REFERENCES ferma(ferma_id),
  CONSTRAINT uq_depozit_ferma_nume UNIQUE (ferma_id, nume)
);

-- 4) CULTURA
CREATE TABLE cultura (
  cultura_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nume         VARCHAR2(60) NOT NULL,
  categorie    VARCHAR2(40),

  CONSTRAINT uq_cultura_nume UNIQUE (nume)
);

-- 5) SEZON
CREATE TABLE sezon (
  sezon_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  an          NUMBER(4) NOT NULL,
  data_start  DATE NOT NULL,
  data_end    DATE NOT NULL,

  CONSTRAINT ck_sezon_date CHECK (data_end > data_start),
  CONSTRAINT uq_sezon_an UNIQUE (an)
);

-- 6) PLANTARE
CREATE TABLE plantare (
  plantare_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcela_id         NUMBER NOT NULL,
  cultura_id         NUMBER NOT NULL,
  sezon_id           NUMBER NOT NULL,
  data_plantare      DATE NOT NULL,
  cant_samanta_kg    NUMBER(10,2),
  hibrid              VARCHAR2(100),

  CONSTRAINT ck_plantare_samanta CHECK (cant_samanta_kg IS NULL OR cant_samanta_kg >= 0),
  CONSTRAINT fk_plantare_parcela FOREIGN KEY (parcela_id) REFERENCES parcela(parcela_id),
  CONSTRAINT fk_plantare_cultura FOREIGN KEY (cultura_id) REFERENCES cultura(cultura_id),
  CONSTRAINT fk_plantare_sezon   FOREIGN KEY (sezon_id)   REFERENCES sezon(sezon_id),

  -- o parcela are o singura cultura pe sezon
  CONSTRAINT uq_plantare_parcela_sezon UNIQUE (parcela_id, sezon_id)
);

-- 7) ANGAJAT
CREATE TABLE angajat (
  angajat_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ferma_id    NUMBER NOT NULL,
  nume        VARCHAR2(120) NOT NULL,
  functie     VARCHAR2(60),
  salariu     NUMBER(10,2) NOT NULL,

  CONSTRAINT ck_angajat_salariu CHECK (salariu > 0),
  CONSTRAINT fk_angajat_ferma FOREIGN KEY (ferma_id) REFERENCES ferma(ferma_id)
);

-- 8) UTILAJ
CREATE TABLE utilaj (
  utilaj_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ferma_id       NUMBER NOT NULL,
  denumire       VARCHAR2(120) NOT NULL,
  tip            VARCHAR2(60),
  data_achizitie DATE,

  CONSTRAINT fk_utilaj_ferma FOREIGN KEY (ferma_id) REFERENCES ferma(ferma_id),
  CONSTRAINT uq_utilaj_ferma_denumire UNIQUE (ferma_id, denumire)
);

-- 9) LUCRARE
CREATE TABLE lucrare (
  lucrare_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plantare_id   NUMBER NOT NULL,
  angajat_id    NUMBER NOT NULL,
  utilaj_id     NUMBER,
  tip_lucrare   VARCHAR2(50) NOT NULL,
  data_lucrare  DATE NOT NULL,
  ore_lucrate   NUMBER(6,2),
  cost          NUMBER(12,2) DEFAULT 0 NOT NULL,

  CONSTRAINT ck_lucrare_ore CHECK (ore_lucrate IS NULL OR ore_lucrate >= 0),
  CONSTRAINT ck_lucrare_cost CHECK (cost >= 0),

  CONSTRAINT fk_lucrare_plantare FOREIGN KEY (plantare_id) REFERENCES plantare(plantare_id),
  CONSTRAINT fk_lucrare_angajat  FOREIGN KEY (angajat_id)  REFERENCES angajat(angajat_id),
  CONSTRAINT fk_lucrare_utilaj   FOREIGN KEY (utilaj_id)   REFERENCES utilaj(utilaj_id)
);

-- 10) STOC (intrari in depozit pentru o plantare)
CREATE TABLE stoc (
  stoc_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  depozit_id     NUMBER NOT NULL,
  plantare_id    NUMBER NOT NULL,
  data_intrare   DATE NOT NULL,
  cantitate_tone NUMBER(12,2) NOT NULL,

  CONSTRAINT ck_stoc_cant CHECK (cantitate_tone >= 0),

  CONSTRAINT fk_stoc_depozit  FOREIGN KEY (depozit_id)  REFERENCES depozit(depozit_id),
  CONSTRAINT fk_stoc_plantare FOREIGN KEY (plantare_id) REFERENCES plantare(plantare_id),

  -- evita duplicate evidente (aceeasi plantare intr-un depozit in aceeasi zi)
  CONSTRAINT uq_stoc UNIQUE (depozit_id, plantare_id, data_intrare)
);
